name: Issue Command Bot

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  process-command:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue on /assign Command
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body.trim();
            const commenter = context.payload.comment.user.login;
            const issueNumber = context.issue.number;

            if (comment === "/assign") {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                assignees: [commenter]
              });
              console.log(`Assigned issue #${issueNumber} to @${commenter}`);
            }
