name: Issue Command Bot

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  process-command:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue on /assign Command
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body.trim();
            const commenter = context.payload.comment.user.login;
            const issueNumber = context.issue.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            if (comment === "/assign") {
              await github.rest.issues.addAssignees({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueNumber,
                assignees: [commenter]
              });

              await github.rest.issues.createComment({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueNumber,
                body: `🛠️ Assigned issue #${issueNumber} to @${commenter}!`
              });

              console.log(`Assigned issue #${issueNumber} to @${commenter} and commented.`);
            }
