name: Issue Command Bot

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  process-command:
    runs-on: ubuntu-latest
    steps:
      - name: Process Commands
        uses: actions/github-script@v6
        with:
          script: |
            const comment = context.payload.comment.body.trim().toLowerCase();
            const commenter = context.payload.comment.user.login;
            const issueNumber = context.issue.number;
            const { owner: repoOwner, repo: repoName } = context.repo;

            const octokit = github; // Use the octokit instance

            // Handle /assign command
            if (comment === "/assign") {
              await octokit.rest.issues.addAssignees({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueNumber,
                assignees: [commenter]
              });

              await octokit.rest.issues.createComment({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueNumber,
                body: `🛠️ Assigned issue #${issueNumber} to @${commenter}!`
              });
            }

            // Handle /close command
            if (comment === "/close") {
              await octokit.rest.issues.update({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueNumber,
                state: "closed"
              });

              await octokit.rest.issues.createComment({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueNumber,
                body: `✅ Issue #${issueNumber} has been closed by @${commenter}.`
              });
            }

            // Handle /label command
            if (comment.startsWith("/label ")) {
              const labelName = comment.replace("/label ", "").trim();

              if (labelName) {
                try {
                  await octokit.rest.issues.addLabels({
                    owner: repoOwner,
                    repo: repoName,
                    issue_number: issueNumber,
                    labels: [labelName]
                  });

                  await octokit.rest.issues.createComment({
                    owner: repoOwner,
                    repo: repoName,
                    issue_number: issueNumber,
                    body: `🏷️ Added label **"${labelName}"** to issue #${issueNumber}.`
                  });
                } catch (error) {
                  if (error.status === 404) {
                    // If label doesn't exist, create it and add it
                    await octokit.rest.issues.createLabel({
                      owner: repoOwner,
                      repo: repoName,
                      name: labelName,
                      color: "0e8a16"  # Green color
                    });

                    await octokit.rest.issues.addLabels({
                      owner: repoOwner,
                      repo: repoName,
                      issue_number: issueNumber,
                      labels: [labelName]
                    });

                    await octokit.rest.issues.createComment({
                      owner: repoOwner,
                      repo: repoName,
                      issue_number: issueNumber,
                      body: `🎨 Created and added label **"${labelName}"** (Color: Green) to issue #${issueNumber}.`
                    });
                  } else {
                    throw error;
                  }
                }
              }
            }
